### ISSUE TITLE
Which fractional derivative does it compute?

### ISSUE THREAD

**Issue by nicolahcm** [fracdiff/fracdiff#113]
Hi, there exist many fractional derivatives,
the most common are the following 3:
1) Conformable fractional derivative
2) Caputo fractional derivative
3) Riemann-Liouville derivative.

I am interested in 3 for some research, which one is refering to your fractional derivative? I couldn't find information

**Comment by ghost** [comment]
Hi, thank you for your interest.

It computes the one referred to in "Advances in Financial Machine Learning " section 5.
Fracdiff here applies to time series a Taylor-expanded operator (1-D)^n where D is a backshift and n is a real number.

**Comment by ghost** [comment]
Hope it resolved. Thank you for asking and please do not hesitate to reopen this.
