### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by TheMightiestCarrot** [fracdiff/fracdiff#128]
Hello,

firstly thanks for this repo :) 
i want to use fracdiff of a price as a featue fed into neural network. 
Do you advise normalizing the data after the fractdiff? 
Does the minimal "d" to pass ADF change in time? Should the minimal "d" be recalculed with new data? (expanding window)
Does fracdiff impose look ahead bias?

Thanks in advance for your answers :)

**Comment by ghost** [comment]
thank you for using :)

> Do you advise normalizing the data after the fractdiff?

yes because neural networks usually need normalized data.

> Does the minimal "d" to pass ADF change in time? Should the minimal "d" be recalculed with new data? (expanding window)

In general yes, e.g. time series undergoing regime shift from mean-reversion to trend-follow.

> Does fracdiff impose look ahead bias?

No per se.

**Comment by TheMightiestCarrot** [comment]
Thank you for your reply :)

> yes because neural networks usually need normalized data.

normalization introduce look ahead bias, do you know how to deal with it? (rolling window norm? what length?)
> In general yes, e.g. time series undergoing regime shift from mean-reversion to trend-follow.

is there some "best practice" when choosing the right window length? What would you recommend?

**Comment by ghost** [comment]
> normalization introduce look ahead bias, do you know how to deal with it? (rolling window norm? what length?)

look ahead bias in the sense of leakage (using test data for fitting)?
as far as you fit with train data normalization does not introduce leakage.

> is there some "best practice" when choosing the right window length? What would you recommend?

depends on domain knowledge - leverage yours :)

**Comment by TheMightiestCarrot** [comment]
>look ahead bias in the sense of leakage (using test data for fitting)?
as far as you fit with train data normalization does not introduce leakage.

min-max normalization causes early data to be scaled by min and max value that is measured later on hence it introduces look ahead bias.
data: 1,2,3,100000,... will look like this after normalization: 0,0,0,1 but in live system when we have only values 1,2,3 we dont know that huge value like 100000 is ahead of us so we use only "known" values 1,2,3 to perform min-max normalization. 

looking at [this](https://raw.githubusercontent.com/fracdiff/fracdiff/main/examples/fig/spx.png) data for example if we performed normalization we would know just right from the start that the biggest drop or peak is ahead of us so it would be obvious to make a decision accordingly

>depends on domain knowledge - leverage yours :)

fair enough :)

**Comment by ghost** [comment]
> min-max normalization causes early data to be scaled by min and max value that is measured later on hence it introduces look ahead bias.

yes that is inevitable and could be a problem depending on the standpoint. i personally do not think it troubles us that much but if you want to suppress the effect of outliers you could use other normalization
