### ISSUE TITLE
Adding .inverse_transform method

### ISSUE THREAD

**Issue by fjaraavilaa** [fracdiff/fracdiff#137]
Hi!
 I must say this module has come as a great relieve, since implementing fractional differenced time series was not very easy. 

But is it possible to have the inverse transformed method like in scikit learn? I have read that might have some numerical complications, but I am not entirely sure.

Regards,
Francisco

**Comment by ghost** [comment]
Hi, thank you for suggestion. Kindly refer to https://github.com/fracdiff/fracdiff/issues/41 please.
