### ISSUE TITLE
trouble grid searching frac diff

### ISSUE THREAD

**Issue by replacementAI** [fracdiff/fracdiff#148]
`
ct = ColumnTransformer([
    ('fracdiff', fractional_differenctiation, [0,1,2,3,4,5])
], remainder='passthrough')
`

`
pipe = Pipeline(steps=[
    ('fracdiff', ct),
    ('model', model)
])
`

`
param_dist = {
    'fracdiff__fracdiff__d': [1/4, 2/4, 3/4, 1],
    'fracdiff__fracdiff__window': [5,10,15,20],
}
`

I have to put fracdiff thru a columntransformer because I dont want it to transform certain columns. When I run the search, I get the following error

`
AttributeError: 'Fracdiff' object has no attribute 'set_params'
`

**Comment by replacementAI** [comment]
This doesnt work when frac diffing the entire thing either
`
AttributeError: 'Fracdiff' object has no attribute 'set_params'
`

`
fractional_differenctiation = Fracdiff()
`
`
pipe = Pipeline(steps=[('fracdiff', fractional_differenctiation),
                          ('model', model)])
`

**Comment by ghost** [comment]
thanks, the latest version 0.9.0 includes your fix #149 for this issue.

**Comment by replacementAI** [comment]
> thanks, the latest version 0.9.0 includes your fix #149 for this issue.

np, glad to help
