### ISSUE TITLE
ENH: Custom stationarity tester

### ISSUE THREAD

**Issue by ghost** [fracdiff/fracdiff#15]
Let users use a custom stationarity tester.
`FracdiffStat` will use a parameter like `stat_tester: callable[[array], bool]` which returns if an array is stationary or not.

**motivation 1**:
There are many ways to test stationarity out there (KPSS and so forth).
With this enhancement, we can let users use arbitrary testers without implementing them in fracdiff.

**motivation 2**:
Currently `FracdiffStat` uses `adfuller` (statsmodels) with default parameters.
`adfuller` by default automatically determines `maxlag`.
This `maxlag` can be too large and significantly slow down the computation (e.g. #14).
In such a case, the user may want to use `adfuller` with smaller `maxlag`.

**Comment by ghost** [comment]
Another motivation: faster implementation of unit-root test (cf. https://github.com/fracdiff/fracdiff/issues/18#issuecomment-834430506)

**Comment by London38** [comment]
Is it possible to implement this unit-root test too?
 https://advancesindifferenceequations.springeropen.com/articles/10.1186/s13662-021-03317-9

thanks for the work done n.n

**Comment by ghost** [comment]
Thank you for sharing a cool paper.

The feature this issue addresses would allow users to make use of user-defined unit-root testers.
Although we are not planning to implement any testers ourselves at this moment, this feature might help you use that.
