### ISSUE TITLE
ENH: A perfomance improvemens

### ISSUE THREAD

**Issue by vinnik-dmitry07** [fracdiff/fracdiff#18]
It is faster to calculate the weights (coefficients) this way (~4.5x faster):
```python
k = np.arange(1, weights_num)
weights = np.concatenate(([1], np.cumprod((k - order - 1) / k)))
```

```python
s = np.tile([1.0, -1.0], -(-weights_num // 2))[:weights_num]
weights = s * scipy.special.binom(order, np.arange(weights_num))
```

Also, consider:
```python
scipy.signal.fftconvolve(array, weights, mode='full')[:array.size]
```

instead of:
```python
scipy.signal.convolve(array, weights, mode='full')[:array.size]
```
It is slightly better on big arrays (x1.05).

P.S. Anyway, your code is the best I have seen in terms of performance, thx.

**Comment by ghost** [comment]
Sounds great!
For the first one, could you let me know the performance comparison between the original implementation and your one for multiple shapes (like, `n_samples=100 - 100000` and `n_features=1 - 1000`)?

**Comment by ghost** [comment]
As for the fftconvolve, enhancement may not be necessary as `convolve` automatically chooses fft or the direct method based on an estimation of which is faster. But anyway I wasn't aware of fft. Thanks a lot for sharing that!
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.fftconvolve.html

**Comment by vinnik-dmitry07** [comment]
> As for the fftconvolve, enhancement may not be necessary as `convolve` automatically chooses fft or the direct method based on an estimation of which is faster. But anyway I wasn't aware of fft. Thanks a lot for sharing that!
> https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.fftconvolve.html

nice

**Comment by vinnik-dmitry07** [comment]
Oh, I forgot, also you can leverage [bashtage/arch](https://github.com/bashtage/arch) for unit root tests. It is much faster and has [DFGLS](https://en.wikipedia.org/wiki/ADF-GLS_test). In addition, you can use scipy.optimize.brentq to search min diff level:
```python
def n_sigma_p(n):
    return 2 * scipy.stats.norm.cdf(-n, 0, 1)


lags_dfgls = DFGLS(d, trend='c').lags
diff_order_dfgls = scipy.optimize.brentq(
    lambda order: DFGLS(
        frac_diff(d, order=order),
        trend='c', lags=lags_dfgls
    ).pvalue - n_sigma_p(n=3),   # ~0.0027  
    a=0, b=1,
)
```

**Comment by vinnik-dmitry07** [comment]
> Sounds great!
> For the first one, could you let me know the performance comparison between the original implementation and your one for multiple shapes (like, `n_samples=100 - 100000` and `n_features=1 - 1000`)?

```python
def test7(self):
    for num in np.logspace(2, 5, num=10, base=10).astype(np.int):
        modes = 2
        res = {m: 0 for m in range(modes)}

        for _ in range(1000):
            for mode in range(modes):
                tic = time.time()
                lib.get_weights(order=0.5, weights_num=num, mode=mode)
                toc = time.time()
                res[mode] += toc - tic
        print(num, round(res[1] / res[0], 3), res)
```

```python
def get_weights(order: float, weights_num: int, mode: int = 0) -> np.ndarray:
    if mode == 0:
        k = np.arange(1, weights_num)
        weights = np.concatenate(([1], np.cumprod((k - order - 1) / k)))
    elif mode == 1:
        s = np.tile([1.0, -1.0], -(-weights_num // 2))[:weights_num]
        weights = s * scipy.special.binom(order, np.arange(weights_num))
    else:
        raise mode
    return weights
```

Values are a bit noisy, but mode 0 is always better.
```
100 1.328 {0: 0.13525390625, 1: 0.17968153953552246}
215 1.657 {0: 0.06282806396484375, 1: 0.10413503646850586}
464 2.327 {0: 0.10336160659790039, 1: 0.24047398567199707}
1000 3.81 {0: 0.06319785118103027, 1: 0.24076128005981445}
2154 9.461 {0: 0.03202319145202637, 1: 0.30297088623046875}
4641 6.223 {0: 0.1282334327697754, 1: 0.7979409694671631}
10000 3.634 {0: 1.0403454303741455, 1: 3.7804715633392334}
21544 5.465 {0: 1.0556106567382812, 1: 5.7684009075164795}
46415 7.846 {0: 1.2103865146636963, 1: 9.496491193771362}
100000 5.355 {0: 5.19026255607605, 1: 27.793802499771118}
```

**Comment by ghost** [comment]
>mode 0 is always better.

Amazing. I honestly didn't expect that because I thought `binom` is somehow optimized. In fact the first implementation was `mode=0`, but I rewrote it using `binom` as it is semantically clearer. For the moment I would prefer this readability over the extreme speed ...

**Comment by ghost** [comment]
> you can leverage bashtage/arch for unit root tests. It is much faster and has DFGLS

Thank you so much for sharing that. I learn a lot from you. https://github.com/fracdiff/fracdiff/issues/15 would enable using it.

> you can use scipy.optimize.brentq to search min diff level

Awesome! The reason why fracdiffstat uses simple binary search is that d_ should be slightly above the threshold.

**Comment by ghost** [comment]
Again, thank you so much for sharing so many clever ideas, @vinnik-dmitry07 ! I learned a lot from you. Closing this issue to preserve the above discussion for reference by future users.

**Comment by vinnik-dmitry07** [comment]
> but I rewrote it using `binom` as it is semantically clearer.

)

> `s = np.tile([1.0, -1.0], -(-weights_num // 2))[:weights_num]`

))


> Awesome! The reason why fracdiffstat uses simple binary search is that d_ should be slightly above the threshold.

Just add atol to the threshold. ie. 
```
diff_order_dfgls = scipy.optimize.brentq(
    lambda order: DFGLS(
        frac_diff(d, order=order),
        trend='c', lags=lags_dfgls
    ).pvalue - (threshold + 1e-8),
    a=0, b=1, atol=1e-8,
)
```
