### ISSUE TITLE
Misc changes

### ISSUE THREAD

**Issue by vinnik-dmitry07** [fracdiff/fracdiff#19]
If you don't mind, could you please rename Fractdiff to FracDiff, as it is two separate words?) Also fdiff -> frac_diff. And I have considered all other libraries: [numpy-fracdiff](https://github.com/ulf1/numpy-fracdiff), [fractional-differentiation-time-series](https://github.com/philipperemy/fractional-differentiation-time-series), [gist](https://gist.github.com/skuttruf/fb82807ab0400fba51c344313eb43466). They all do the same (use slices of array multiplied by weights) instead of one exception _fractional-differentiation-time-series_ has fft like this:
```python
next_pow2 = np.int(np.power(2, np.ceil(np.log2(2 * array.size - 1))))
dx = np.fft.ifft(np.fft.fft(array, n=next_pow2) * np.fft.fft(weights, n=next_pow2))
res = np.real(dx[:array.size])
```
But It is exactly what scipy.signal.convolve_fft does, and It is slower than scipy.signal.convolve_fft.
So you can state in the readme that this lib performs better than other available (even list them).
And one more thing: if you moved the repo permanently--clean the original readme with a link-message to a new one, don't just add a link to the description.

**Comment by ghost** [comment]
>could you please rename Fractdiff to FracDiff, as it is two separate words?) Also fdiff -> frac_diff

Nice. Both names have pros/cons. Let me value backward compatibility though...

>you can state in the readme that this lib performs better than other available (even list them)

Yeah, although I'm not bold enough to explicitly claim superiority to the other libraries, listing them would be helpful for users to compare among them.

> And one more thing: if you moved the repo permanently--clean the original readme with a link-message to a new one, don't just add a link to the description.

Exactly. I've been lazy... I'll do it before long!
