### ISSUE TITLE
Some thoughts about minimal order and expanding window

### ISSUE THREAD

**Issue by vinnik-dmitry07** [fracdiff/fracdiff#27]
## About minimal order

When we do convolution, we replace infinite sum with finite one [[1]](https://en.wikipedia.org/wiki/Convolution#Circular_discrete_convolution), and we cannot do this for every diffrencing order. We should understand that the cummulative sum of weights must converge to 0. Let us consider two examples:

1) `plt.plot(np.cumsum(lib.get_weights(order=0.5, weights_num=1555218)))`
![image](https://user-images.githubusercontent.com/24797359/120182683-5f124000-c217-11eb-8e0d-2eae4f0c1d63.png)

![image](https://user-images.githubusercontent.com/24797359/120182864-a3054500-c217-11eb-8281-d8a9216c4862.png)
-- Looks good. The right edge of the monotonically decreasing curve is located near 0.00045.

2) `plt.plot(np.cumsum(lib.get_weights(order=0.1, weights_num=1555218)))`
![image](https://user-images.githubusercontent.com/24797359/120183390-4eae9500-c218-11eb-922b-a84f2b63bd94.png)
-- Oh no, we have positive shift here, because right edge is located near 0.225!

**Solution**
In my code I have following code:
```python
# https://en.wikipedia.org/wiki/68–95–99.7_rule
def n_sigma_p(n=3):
    return 2 * scipy.stats.norm.cdf(-n, 0, 1)


min_order = scipy.optimize.brentq(
    lambda order: np.cumsum(lib.get_weights(order, weights_num=len(df)))[-1] - lib.n_sigma_p(n=3),
    a=0, b=1,
)
```
For array of size 1555218, min_order ~= 0.388. 

## About expanding window

1. I don't know situations when fixed window leads to better results than expanding.

2. `The beginning window_ - 1 elements in output are filled with numpy.nan.`
In my opinion, for financial data, it is preferable to use edge [padding](https://numpy.org/doc/stable/reference/generated/numpy.pad.html)

```python
plt.plot(array, label='array')
plt.plot(np.pad(array, pad_width=(padding_width, 0), mode='edge'), label='edge-padded')
plt.plot(np.pad(array, pad_width=(padding_width, 0), mode='constant', constant_values=0), label='zero-padded')
plt.legend()
```
![image](https://user-images.githubusercontent.com/24797359/120188220-84ef1300-c21e-11eb-910c-681efdc4b81a.png)

Why do we need that? -Because if we dont perform _edge_ padding, the result of convolution will be similar to _zero-padded_, which leads to _boundary effects_ (_edge effects_, _shift_, _distortion_):

```python
plt.plot(scipy.signal.convolve(array, weights)[:array.size], label='zero-padded convolution')

padding_width = len(weights) - 1
padded_array = np.pad(array, pad_width=(padding_width, 0), mode='edge')
plt.plot(scipy.signal.convolve(padded_array, weights)[padding_width:padding_width + array.size], label='edge-padded convolution')

plt.legend()
```
![image](https://user-images.githubusercontent.com/24797359/120189595-38a4d280-c220-11eb-9e37-2ed907b2b6a5.png)
![image](https://user-images.githubusercontent.com/24797359/120189692-5114ed00-c220-11eb-9759-e8999524bdbc.png)

**Comment by ghost** [comment]
Thank you for sharing that! 👍
